<?php

namespace Wbc\AdministratorBundle\Repository;

/**
 * BloqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BloqueRepository extends \Doctrine\ORM\EntityRepository
{
}
