<?php

namespace Wbc\AdministratorBundle\Repository;

/**
 * EjecutarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EjecutarRepository extends \Doctrine\ORM\EntityRepository
{
}
