<?php

namespace Wbc\AdministratorBundle\Repository;

/**
 * PalabraReservadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PalabraReservadaRepository extends \Doctrine\ORM\EntityRepository
{
}
