<?php

namespace Wbc\AdministratorBundle\Repository;

/**
 * PendienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PendienteRepository extends \Doctrine\ORM\EntityRepository
{
}
