<?php

namespace Wbc\AdministratorBundle\Repository;

/**
 * PoliticaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoliticaRepository extends \Doctrine\ORM\EntityRepository
{
}
