language: php

php:
    - 5.5

services:
  - mysql

before_script:
  - mysql -e 'create database IF NOT EXISTS travis;' -utravis
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer self-update
  - composer install
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  # - phpunit -c app

notifications:
  email:
    -  rodmar.zavala@gmail.com