Wbc\AdministratorBundle\Entity\PalabraReservada:
    type: entity
    table: palabra_reservada
    repositoryClass: Wbc\AdministratorBundle\Repository\PalabraReservadaRepository
    id:
        id:
            type: integer
            id: true
    fields:
        nombre:
            type: string
            length: '100'
        descripcion:
            type: string
            length: '500'
            nullable: true
    oneToMany:
      ejecutar:
        targetEntity: Ejecutar
        mappedBy: palabra_reservada
    lifecycleCallbacks: {  }
