Wbc\AdministratorBundle\Entity\Politica:
    type: entity
    table: politica
    repositoryClass: Wbc\AdministratorBundle\Repository\PoliticaRepository
    id:
        id:
            type: integer
            id: true
    fields:
        nombre:
            type: string
            length: '200'
        descripcion:
            type: string
            length: '500'
            nullable: true
    oneToMany:
      configuracion:
        targetEntity: Configuracion
        mappedBy: politica
    lifecycleCallbacks: {  }
